language: elixir
elixir:
  - 1.7.0-dev
otp_release:
  - 20
cache:
  directories:
    - _build
    - deps
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - mix test
  - mix credo
  - mix inch --pedantic
  - mix dialyzer
