language: elixir
elixir:
  - 1.6
otp_release:
  - 20.0
cache:
  directories:
    - _build
    - deps
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - mix test
  - mix credo
  - mix dialyzer
  # - mix inch --pedantic
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json -u

after_success:
  - bash <(curl -s https://codecov.io/bash)
